# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# CENTOS_IMAGE
# CI_COMMIT_TAG
# CI_BUILD_TOKEN
# DOCKER_IMAGE
# DOCKER_USER
# DOCKER_PASS
# DIND
# GO_IMAGE
# REGISTRY
# REGISTRY_IMAGE
# PKI_URL
# ORG

services:
  - ${DIND}

stages:
# - test
  - package

# Uncomment once we can get an image with docker and go working
#test:
#  image: $CENTOS_IMAGE
#  stage: test
#  script:
#    - yum install golang -y
#    - yum install docker -y
#    - docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/auth:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd $REGISTRY_IMAGE
#    - ./build-test-images.sh
#    - go test ./...
#  only:
#    - master

package:
  image: ${DOCKER_IMAGE}
  stage: package
  script:
    - docker login -u ${DOCKER_USER} -p "${DOCKER_PASS}" $REGISTRY
    - docker build --build-arg IMAGE=$GO_IMAGE . -t $REGISTRY/$ORG/seed-common:latest
    - docker push $REGISTRY/$ORG/seed-common:latest