# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# CENTOS_IMAGE
# CI_COMMIT_TAG
# DOCKER_IMAGE
# DIND
# $CI_BUILD_TOKEN
# REGISTRY
# ORG

services:
  - ${DIND}

stages:
#  - test
  - package

#test:
#  image: $CENTOS_IMAGE
#  stage: test
#  script:
#    - yum install golang -y
#    - yum install docker -y
#    - docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/auth:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd registry:2
#    - ./build-test-images.sh
#    - go test ./...
#  only:
#    - master

package:
  image: ${DOCKER_IMAGE}
  stage: package
  dependencies:
    - silo-build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build --build-arg IMAGE=$GO_IMAGE . -t $REGISTRY/$ORG/seed-common:$CI_COMMIT_TAG
    - docker push $REGISTRY/$ORG/seed-common:$CI_COMMIT_TAG
  only:
    - tags
